[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "python311Packages.virtualenv"]

[phases.install]
cmds = [
  "python -m venv /opt/venv",
  "/opt/venv/bin/pip install -r backend/requirements.txt",
  "/opt/venv/bin/playwright install chromium"
]

[start]
cmd = "cd backend && /opt/venv/bin/uvicorn main:app --host 0.0.0.0 --port $PORT"