[build]
builder = "nixpacks"

[deploy]
startCommand = "cd backend && pip install -r requirements.txt && playwright install chromium && uvicorn main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"